sudo: false

dist: trusty
language: elixir
elixir:
  - 1.5
addons:
  postgresql: 9.4 # TODO: look at upgrading this
cache:
  directories:
    - _build
    - deps
    - assets/node_modules
    - assets/elm-stuff/build-artifacts
    - assets/elm-stuff/packages
    - sysconfcpus
env:
  - MIX_ENV=test ELM_VERSION=0.18.0
before_install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
  - mix do local.hex --force, local.rebar --force
  - mix do deps.get, compile, ecto.create, ecto.migrate
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  # Taken from: https://github.com/rtfeldman/node-test-runner#travis-ci
  - npm install -g elm@$ELM_VERSION elm-test
  - git clone https://github.com/NoRedInk/elm-ops-tooling apps/av_web/assets/elm-ops-tooling
  - cd apps/av_web/assets && elm-ops-tooling/with_retry.rb elm package install --yes && cd -
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
script:
  - mix coveralls.json
  - cd assets && npm test && cd -
after_success:
  - bash <(curl -s https://codecov.io/bash)

