#!/bin/bash

set -e

if [[ $NEW_NAME = "" ]] || [[ $NEW_OPT = "" ]];then
  echo "please run this commad with NEW_NAME and NEW_OPT vars"
  echo "for example, for the new name of MyApp, you would run:"
  echo "NEW_NAME=MyApp NEW_OPT=my_app ./rename"
fi

CURRENT_NAME="Pete"
CURRENT_OTP="pete"

ack -l $CURRENT_NAME | xargs sed -i '' -e "s/$CURRENT_NAME/$NEW_NAME/g"
ack -l $CURRENT_OTP | xargs sed -i '' -e "s/$CURRENT_OTP/$NEW_OTP/g"

mv lib/$CURRENT_OTP lib/$NEW_OTP
mv lib/$CURRENT_OTP.ex lib/$NEW_OTP.ex
mv lib/${CURRENT_OTP}_web lib/${NEW_OTP}_web
mv lib/${CURRENT_OTP}_web.ex lib/${NEW_OTP}_web.ex
