#!/bin/bash

set -e

if [ -d "$HOME/pete_boilerplate_tmp" ];then
  echo "$HOME/pete_boilerplate_tmp already exists, please delete it for script to work"
  exit 1
fi

PETE_BOILERPLATE_CURRENT_DIR="$(pwd)"

if [ -d "$PETE_BOILERPLATE_CURRENT_DIR/../$1" ];then
  echo "There exists directory $PETE_BOILERPLATE_CURRENT_DIR/../$1"
  echo "This would be overwritten, please change the name of this directory before continuing"
  exit 1
fi

if [[ $1 = "" ]] || [[ $1 = "help" ]];then
  echo $'available boilerplates are:\nauth\nadmin_auth\npete_auth'
elif [[ $1 = "auth" ]] || [[ $1 = "admin_auth" ]] || [[ $1 = "pete_auth" ]]; then
  echo "You've selected boilerplate: $1"
  mkdir -p "$HOME/pete_boilerplate_tmp"
  mv "$1" "$HOME/pete_boilerplate_tmp/$1"
  cd ..
  rm -rf "$PETE_BOILERPLATE_CURRENT_DIR"
  mv "$HOME/pete_boilerplate_tmp/$1" .
  rm -rf "$HOME/pete_boilerplate_tmp"
  cd "$1"
  echo "configured boilerplate: $1"
else
  echo "Unknown command; please run ./select help for more info"
fi
